### ISSUE TITLE
Web app in chapter 10 - default Microsoft site is loaded

### ISSUE THREAD

**Issue by pauldj54** [fouldsy/azure-mol-samples-2nd-ed#3]
Hi, 
I created a web app in order to show the pizzas stored in the cosmos db instance. 
When I open the app in the browser I can only see the Microsoft default page. 
After some minutes nothing is shown and I got an "Application Error":
![image](https://user-images.githubusercontent.com/706754/77855101-a6a1d400-71ee-11ea-9a79-d1dccb86c699.png)
If a clone it locally and started it in my laptop, it works as expected.

How can I debug it?

I open a SSH Session and can confirm that express app is running.

Best, 
Paul

**Comment by ArtemProc** [comment]
+1
Some issue starting during Container warm up
'See container logs for debugging'

**Comment by ybeltrikov** [comment]
yep, same error

**Comment by barbeer** [comment]
Here's the issue:
https://github.com/fouldsy/azure-mol-samples-2nd-ed/blob/master/10/cosmosdbwebapp/app.js#L23

`process.env.PORT` should be used instead of hardcoded 3000

Created PR: https://github.com/fouldsy/azure-mol-samples-2nd-ed/pull/7

**Comment by fouldsy** [comment]
Thanks, @barbeer. PR has merged.
