### ISSUE TITLE
Second version of the book has low quality images

### ISSUE THREAD

**Issue by arkfen** [fouldsy/azure-mol-samples-2nd-ed#6]
Yeah, I know, it is not the code issue, but book itself but I did not find any other way to communicate the fact (which maybe already known) that some listing images in the second edition so low quality - you can not actually see a thing... please double check and edit the book if possible. good luck!

**Comment by fouldsy** [comment]
Sorry, I don't have control over the post-production process, you'd need to reach out to Manning support - https://www.manning.com/support. I haven't heard anyone else with issues, and there's been a lot of copies of the eBook / liveBook sold, so it may have just been something in the download process. The support folks at Manning should be able to provide a replacement version that lets you see the images.
